---
title: "Active Francization on the Knowledge of Canadian Official Languages in Quebec from 2001 to 2021"
author: Denise Chang
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "Despite the adoption of the Official Languages Act in 1969, Quebec is the only province to recognize French as its sole official language in Canada. This paper investigates the knowledge of canadian official langauges in Quebec using data from Canadian Language censuses from 2001 to 2021. The exploration of the data suggests that the Language policies and the active francization of Quebec contributes to a higher bilingualism in the province. The results of this study are significant, as official bilingualism is closely tied to Canada's history and cultural identity. Promoting bilingualism is also important as it fosters understanding between English- and French-speaking communities. "
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction
In 1969, Canada adopted the Official Languages Act which recognizes both English and French as its official languages [CITE SMT]. Though Canada is a bilingual country, seven provinces recognizes English as their sole official language, and one province considers their official language to be French. New-Brunswick is the only bilingual province [CITE SMT]. To encourage bilingualism, English-speaking provinces promote French as second language through educational programs, such as the French Immersion Program in Ontario. However, the French-speaking province, Quebec, restricts the usage of English. Instead, Quebec pushes forward programs and policies to further promote the French language [CITE SMT]. Quebec's active francization which differentiates it from the rest of Canada sparks debate in the population as it seems to go against Canadian bilingualism. 

In this paper, I am interested in the evolution of the knowledge of canadian official languages in Quebec. Using data from the Canadian Language Census from 2001, 2006, 2011, 2016 and 2021, I explore the trends in Quebecers' knowledge in English and French for more insights on the influence of the government's francization efforts on the provincial bilingualism rate. I find that, despite the restriction on the usage of English in Quebec, the province has an increasing trend in bilingual population. MODIFY THIS IF NEEDED AFTER DISCUSSION

The remainder of this paper is structured as follows. Section 2 discusses the data collection and the studied variables. Section 4 builds a model that illustrates the trend in bilingualism rate in Quebec throughout 



# Data


Talk more about it.

Talk way more about it. 



# Model

The goal of our modelling strategy is twofold. Firstly,...

Here we briefly describe the Bayesian analysis model used to investigate... Background details and diagnostics are included in

## Model set-up

Define $y_i$ as the number of seconds that the plane remained aloft. Then $\beta_i$ is the wing width and $\gamma_i$ is the wing length, both measured in millimeters.  

\begin{align} 
y_i|\mu_i, \sigma &\sim \mbox{Normal}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta_i + \gamma_i\\
\alpha &\sim \mbox{Normal}(0, 2.5) \\
\beta &\sim \mbox{Normal}(0, 2.5) \\
\gamma &\sim \mbox{Normal}(0, 2.5) \\
\sigma &\sim \mbox{Exponential}(1)
\end{align}

We run the model in R [@citeR] using the `rstanarm` package of @rstanarm. We use the default priors from `rstanarm`.


### Model justification

We expect a positive relationship between the size of the wings and time spent aloft. In particular...

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results

Our results are summarized in.



# Discussion

## First discussion point

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

# References


